choco install -y --force vcredist2010
choco install -y --force vcredist2012
choco install -y --force wamp-server
choco install -y --force vim
choco install -y --force atom
choco install -y --force sublimetext3
choco install -y --force notepadplusplus
choco install -y --force firefox
choco install -y --force googlechrome
choco install -y --force ruby
choco install -y --force nodejs
choco install -y --force sudo
choco install -y --force putty.portable
